### ISSUE TITLE
Classifying unknown images

### ISSUE THREAD

**Issue by boycepn** [mikeyEcology/MLWIC#20]
Hello, 

I'm sorry this likely a stupid question but I just wanted clarification. Once you have trained a satisfactory model on a subset of your own images,  if you want to try to classify the rest of a data set for which you haven't manually classified species, is the process "simply" to label each image as species unknown (0) and run the classify function? I feel like I'm missing something here?

Cheers,
Paul

**Comment by mikeyEcology** [comment]
Yes-you are understanding correctly. If you don't know what's in the images you can label them as 0 (or as any number that is a class ID in your dataset). It doesn't matter what is in the second column of the file because the model won't be looking at it when it classifies images. You only need to have a second column there for consistency among files.

**Comment by boycepn** [comment]
Brilliant! thanks so much for the clarification and the quick response.
